name: CI Test

on: [push]

jobs:
  sast_scan:
    name: Run Bandit
    runs-on: ubuntu-latest

    steps:
      - name: Checksout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python_version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r .
